### ISSUE TITLE
I'm not able to checkout or update this repo

### ISSUE THREAD

**Issue by mwarger** [aws-amplify/community#111]
![image](https://user-images.githubusercontent.com/686823/59931530-c6f46500-940a-11e9-9d83-a128b2a684ab.png)

I see the above when checking out using GitKraken on windows 10.  Seems like there could be an invalid character in the filename?  Please advise.

**Comment by swaminator** [comment]
@mwarger this has been fixed with this: https://github.com/aws-amplify/community/pull/113 commit. Please try it again.

**Comment by mwarger** [comment]
This worked.  Thank you.

**Comment by mwarger** [comment]
Just kidding.  I tried to update my fork, but that didn't work.  I deleted the fork and the local version.  I then forked it again and tried to clone it - received the same error.

**Comment by mwarger** [comment]
@swaminator Any advice for this?  I would like to add a couple of articles, but I wasn't able to clone this repo.  I will try again this week.

**Comment by mwarger** [comment]
This worked for some reason.  I dunno.
