### ISSUE TITLE
Events dates are off by one day when running locally 

### ISSUE THREAD

**Issue by sebsto** [aws-amplify/community#17]
When running the web site locally, all events are off by one day.
I guess this is a due to a local timezone, my laptop is running in 
```
Central European Summer Time
Time zone in Paris, France (GMT+2) 
```

Here is a screenshot of the hosted version :
<img width="923" alt="image" src="https://user-images.githubusercontent.com/401798/57179513-91a1b100-6e76-11e9-89a4-ec7fcf2add78.png">

Here is a screenshot of my local version :
<img width="925" alt="image" src="https://user-images.githubusercontent.com/401798/57179521-9e260980-6e76-11e9-8cc5-79b9a6a7a115.png">

**Comment by harrysolovay** [comment]
@sebsto thank you for calling attention to this. We'll hopefully be able to internationalize soon. Incase you wanted to take a crack at it, a PR would be tremendous (& if not, no worries 👍 ).

Any library recommendations? `react-intl` and `react-i18next` seem to be popular solutions. It would be great to hear your thoughts.

Thanks again for submitting this issue!

**Comment by harrysolovay** [comment]
@sebsto I'm curious if you're still running into this problem––seems like the problem was in part caused by the way newsletters were being generated. We re-created the generation mechanism last week. Hoping this is now resolved.

**Comment by sebsto** [comment]
Thanks for getting back to me.  Yes, I still observe the same with latest code in master branch. 
Here are two screenshots.  First from local version and second from hosted version.
<img width="1429" alt="Screenshot 2019-05-31 at 10 17 11" src="https://user-images.githubusercontent.com/401798/58691842-6f278880-838d-11e9-827f-22b7bf4c59f2.png">
<img width="1424" alt="Screenshot 2019-05-31 at 10 17 17" src="https://user-images.githubusercontent.com/401798/58691847-7189e280-838d-11e9-8c49-a4dd02225693.png">

**Comment by sebsto** [comment]
I changed my Cloud9 machone's TZ (following instructions at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html) 

```
$ date 
Fri May 31 12:00:52 CEST 2019
```
And can reproduce the problem.  
<img width="591" alt="image" src="https://user-images.githubusercontent.com/401798/58698861-6ee2b980-839c-11e9-9200-922ce77048b1.png">

So, it is pretty easy for you to reproduce, just spawn a Cloud9 or EC2 instance, change the timezone and voila ! :-)

**Comment by harrysolovay** [comment]
@sebsto this is extremely helpful. Will get back to you about this soon.

**Comment by sebsto** [comment]
I am trying to nail down the root cause, but I am new to Gatsby and I am slow on this :-) 
Looks like the data returned the Gatsby GraphQL API is incorrect.  So *I think* this is not a rendering issue as I initially supposed, but the root cause lies probably in the module (a Gatsby module?) that reads the Markdown and exposes it through GraphQL.

Here is my GraphQL query executed in GraphiQL : 
```graphql
fragment Contributor on MarkdownRemark {
    fields {
      key
      slug
    }
    frontmatter {
      name
      bio
      github
      twitter
      website
    }
  }
  
  fragment SharedBetweenPostsAndEvents on MarkdownRemark {
    fields {
      key
      slug
      date(formatString: "MMMM D, YYYY")
    }
    frontmatter {
      href
      title
      description
      tags
    }
  }

fragment Event on MarkdownRemark {
    ...SharedBetweenPostsAndEvents
    fields {
      attendants {
        ...Contributor
      }
    }
    frontmatter {
      city
      country
    }
  }
 
  query($currentDate: Date!) {
    allMarkdownRemark(
      sort: {fields: [fields___date], order: ASC}
      filter: {fields: {category: {eq: "events"}, date: {gt: $currentDate}}}
    ) {
      edges {
        node {
          ...Event
          frontmatter {
            platforms
          }
        }
      }
    }
  }
```

with 
```json
{ "currentDate": "2019-06-01" }
```

And here is a result extract :

```json
{
          "node": {
            "fields": {
              "key": "uActwvwBgN5",
              "slug": "events/2019/06/11/devdays",
              "date": "June 10, 2019",
              "attendants": [
                {
                  "fields": {
                    "key": "2vIVgGdj121",
                    "slug": "contributors/sebastien-stormacq"
                  },
                  "frontmatter": {
                    "name": "Sébastien Stormacq",
                    "bio": "Technical Evangelist @ AWS France.  Talk about frontend, serverless and identity.  https://stormacq.com",
                    "github": "sebsto",
                    "twitter": "sebsto",
                    "website": null
                  }
                }
              ]
            }
```

As you can see : 
```
"slug": "events/2019/06/11/devdays",
"date": "June 10, 2019",
```
The directory name is correctly parsed as `2019/06/11` but the date returned is `2019/06/10`

**Comment by sebsto** [comment]
BTW, I don't think it is related, but most of the `onCreateNode` code is never executed because this condition is always false https://github.com/aws-amplify/community/blob/master/gatsby-node/onCreateNode.js#L13

But the date received here is already incorrect : 
```json
"context": {
    "slug": "events/2019/07/26/addc",
    "date": "2019-07-25T22:00:00.000Z"
  },
```

**Comment by harrysolovay** [comment]
@sebsto I don't believe so; `node.internal.type === 'MarkdownRemark'` is often true... did you mean to highlight another condition? Can you please describe the problem another way?––I don't think I understand.

Also, in regards to the timezone problem, the solution would probably be to generate many builds for different time zones and feed them up depending on the client. This could be tough to implement. I can't find pre-existing conversations about this problem in Gatsby projects. Feels like a problem with the build paradigm itself. Any other ideas on how we might be able to solve this issue without doing anything at runtime?

**Comment by sebsto** [comment]
Regarding the date : Gatsby is returning an incorrect date.  It takes the date from the slug (2019-07-26) in this example.  It consider the time as being 00:00am GMT.  Then it applies the timezone conversion according to client's timezone (for me GMT+2) to calculate the GMT / Zulu time, which produce a date 2h before **the previous day** (2019-07-25 22:00 Zulu time) 

```
"context": {
    "slug": "events/2019/07/26/addc",
    "date": "2019-07-25T22:00:00.000Z"
  },
```

When the build machine has a local TZ in GMT, the problem does not appear.  This is why the public web site is correct.

I would suggest to modify the Gatsby module to not make that time conversion.  But this is potentially a breaking change for other Gatsby apps.

I don't like the idea to generate multiple builds, for each different timezone (24 !)  The design best practice is to store time in Zulu time and display in local time to the client app.  TZ rendering should be a front end issue.  Ideally, Gastby must return the GMT time and we should have client side code to convert it to local or not.

Regarding this use case, we can safely assume that event organisers are always going to give the date of their event / conference in local time and people interested to attend the conference are only interested by local time only.  So if Gatsby returns whatever the event organiser entered, without conversion, we will be good.

**Comment by harrysolovay** [comment]
@sebsto good call & agreed. Thank you for the deep dive! Will fix this asap.
