### ISSUE TITLE
re:invent event

### ISSUE THREAD

**Issue by wizage** [aws-amplify/community#189]
Add re:invent event to the events page as well include a guide with all of the sessions that are diving into Amplify/GraphQL.

**Comment by timrchavez** [comment]
I'm headed to re:invent. Is there an event for the AWS Amplify developer/user community? Didn't see it at https://amplify.aws/community/events (yet)

**Comment by swaminator** [comment]
@timrchavez @wizage here it is: https://amplify.aws/community/events/2019/12/02/re:Invent/
