### ISSUE TITLE
Can we get a developer focused chat channel for higher bandwith, real-time communication and collaboration?

### ISSUE THREAD

**Issue by timrchavez** [aws-amplify/community#190]
Unless I'm missing something, there seems to be a lot of separation between AWS employees developing on AWS Amplify and its open source contributors (the primary common ground being PRs and Issues). It would be nice to have a higher bandwidth communication option like a chat channel where open source contributors to the project can discuss their implementation plans and details in the open with AWS developers. This, I think, would improve collaboration (maybe even increase contributions?), provide mentorship opportunities, and foster a deeper sense of community. We currently have https://gitter.im/AWS-Amplify/Lobby which seems to be more oriented towards user support than active/on-going development. Could we maybe get something development focused?

**Comment by mauerbac** [comment]
Hey @timrchavez - correct, we have the Gitter for now. I'll be working on adding new real-time community resources in the near future. Stay tuned!
