### ISSUE TITLE
No answer from aws-amplify-customer@amazon.com

### ISSUE THREAD

**Issue by khalidbourhaba** [aws-amplify/community#229]
Hello, 

i've sent an email to aws-amplify-customer@amazon.com, as mentioned [here ](https://github.com/aws-amplify/community/blob/master/content/events/README.md). But i didn't get an answer.

Could you please check ?  

Thanks

**Comment by khalidbourhaba** [comment]
cc @swaminator

**Comment by simpson** [comment]
Same

**Comment by gsans** [comment]
Hi @simpson ! Ping me on Twitter @gerardsans and I'll take your details. Delivery is a bit delayed though due to current restrictions.

**Comment by simpson** [comment]
thanks @gsans ! Just DMed you

**Comment by mauerbac** [comment]
Looks like @gsans will help. Closing out.
