### ISSUE TITLE
Looking for Help for a discord Channel

### ISSUE THREAD

**Issue by arhoy** [aws-amplify/community#236]
I am wondering if there is a current discord channel to help and talk to others regarding aws amplify

**Comment by jakobpack** [comment]
They have a Gitter channel: [gitter.im/AWS-Amplify](https://gitter.im/AWS-Amplify/Lobby).

**Comment by mauerbac** [comment]
Hey @arhoy - we have a Gitter channel for now. Trying to add other communities like Discord in the future. Stay tuned!
