### ISSUE TITLE
How do I filter subscriptions with ids on graphql appsync API?

### ISSUE THREAD

**Issue by anand-010** [aws-amplify/community#272]
My problem is more related to a real-time chat application with multiple chat rooms.
I want to filter each message and send it to users who subscribed to the same chatrooms. (not filtering on client-side)

I am a beginner to app sync. How do I do that Please help me?

Please give me relevant links, codes or steps.

**Comment by gsans** [comment]
I think you may be able to achieve what you need using subscription arguments.
https://docs.aws.amazon.com/appsync/latest/devguide/real-time-data.html#using-subscription-arguments

This is not an issue for this repository so I'm going to close it. For AppSync related questions you can use [AppSync Community](https://github.com/aws/aws-appsync-community/issues).

**Comment by dabit3** [comment]
Check out the guide we have created for this as well: "How to create GraphQL subscriptions by id"

https://docs.amplify.aws/guides/api-graphql/subscriptions-by-id/q/platform/js

**Comment by anands9288907423** [comment]
I am using Angular as framework. I added this code to schema.
type Subscription {
  onaddtodoById(id: ID!): Todo
    @aws_subscribe(mutations: ["createTodo"])

it automatically generated api files for me. 

  OnaddtodoByIdListener: Observable<OnaddtodoByIdSubscription> = API.graphql(

    graphqlOperation(
      `subscription OnaddtodoById($id: ID!) {
        onaddtodoById(id: $id) {
          __typename
          id
          name
          description
          address
          createdAt
          updatedAt
        }
      }`
    )
  ) as Observable<OnaddtodoByIdSubscription>;

it showed the subscription as a variable. 
i can't even pass id into it i am searched a lot.
I lost my mind.
I quit. 
appolo manual configuration is the best.

**Comment by gsans** [comment]
From the bits you shared I have created a code snippet that should work for you using Angular. Make sure you have the dependency `npm install zen-observable`

https://gist.github.com/gsans/aeffbae886add35b669c84f5e5b3fa69

Let me know if that works.

**Comment by anand-010** [comment]
I think you selected typescript insted of angular
When we select typescript it will generate grapql folder with types as ts file.
but i am selected angular it will generate .graphql files and a APIservice.ts it contains the auto generated codes.
![image](https://user-images.githubusercontent.com/32414977/89294223-d40afc80-d67c-11ea-9a6f-c7299625b5a9.png)
I cant import it like you do.

**Comment by anand-010** [comment]
This is the APIservice.ts file.
https://pastebin.com/dpQu1feW

**Comment by gsans** [comment]
It's a bit difficult to diagnose without looking at the code. Your files should contain the query either using GraphQL or a generated API. Try with one or the other and share your code so I can help you further. You can also reach me via DM on Twitter @gerardsans for quicker feedback

**Comment by anand-010** [comment]
I am posted the sample code on github
https://github.com/anand-010/amplify_test

**Comment by gsans** [comment]
Thanks for that. I've look into the generated code and it doesn't support passing arguments as confirmed by this issue
https://github.com/aws-amplify/amplify-cli/issues/2552

Let me try to refactor the code to include the argument for you.

**Comment by gsans** [comment]
This is the gist updated. This is not using the generated API as it doesn't support subscription arguments yet.

Note you need to create different subscriptions one for each different id.

https://gist.github.com/gsans/aeffbae886add35b669c84f5e5b3fa69

**Comment by anand-010** [comment]
I am tried this before
![image](https://user-images.githubusercontent.com/32414977/89301168-f0ac3200-d686-11ea-8d9e-46f8bf5654e5.png)
we cannot input query , variables into API.graphql function
we can pass it like an object 
if then i don't know pass query as a string or other object

**Comment by anand-010** [comment]
Thank you it works
i am wrap it inside an object.
OnaddtodoByIdListener(id:String): Observable<OnaddtodoByIdSubscription>{
    return API.graphql({

      query:`subscription OnaddtodoById($id: ID!) {
             onaddtodoById(id: $id) {
               __typename
               id
               name
               description
               address
               createdAt
               updatedAt
             }
           }`,
           variables: {
             id: id
           }
  
      }) as Observable<OnaddtodoByIdSubscription>;
  } 

Thank you.

**Comment by gsans** [comment]
Good catch. That's it. Happy to help.
