### ISSUE TITLE
AuthError : Confirmation code cannot be empty ! - While using Auth.confirmSignUp

### ISSUE THREAD

**Issue by rajinonnet** [aws-amplify/community#279]
Hey Guys,

I am getting following error consistently.  

I even converted the **verification code** in to **int** before call, still no luck ? 

![image](https://user-images.githubusercontent.com/64529654/91764042-39a6c600-ebf4-11ea-879a-6b7b2b8203a8.png)

```
try { 
          console.log("........2.....handleVerificationCode. : ");
          console.log(parseInt(this.state.verificationCode));

          let codeInt = parseInt(this.state.verificationCode);
          const confirmSignUpResponse = await Auth.confirmSignUp(
                    {
                        username:this.state.email,
                        code:codeInt 
                    } 
               );
                console.log(confirmSignUpResponse);
        } catch (error ) {
            console.log("ERROR OCCURRED !!! ! ! !  ! ");
            this.setState({
              errors: { ...this.state.errors,cognito:error }
            });
        }
```

Would really appreciate any help to resolve this issue.

Thanks

**Comment by Ricardo1980** [comment]
We need more context.

According to this, the code should be a string:
https://aws-amplify.github.io/amplify-js/api/classes/authclass.html#confirmsignup

Try to add this:
console.log("-----state: " + state);

And show us what you can see in CloudWatch when you execute the method that fails.

**Comment by rajinonnet** [comment]
@Ricardo1980 

Thanks for your reply 

I did try with string initially, but no luck !

![image](https://user-images.githubusercontent.com/64529654/91766433-357ca780-ebf8-11ea-9267-b273da03b22f.png)

I am printing the state here after verification code, but it still throws error.

```
        try { 

         console.log("........2.....handleVerificationCode. : ");
         console.log(this.state.verificationCode);
         console.log(this.state)

          const confirmSignUpResponse = await Auth.confirmSignUp(
                    {
                        username:this.state.email,
                        code:this.state.verificationCode,
                        options : { forceAliasCreation: true }
                    }    
               );
                console.log(confirmSignUpResponse);
            
        } catch (error ) {
            console.log("ERROR OCCURRED !!! ! ! !  ! ");
            this.setState({
              errors: { ...this.state.errors,cognito:error }
            });
        }

```

My state still holds other fields like email, password...etc, is this an issue ?

**Comment by Ricardo1980** [comment]
I dont see "state" in that cloudwatch log. 

Can you copy/paste the full cloudwatch log instead of a picture?
Print also the event the lambda function is receiving.

**Comment by rajinonnet** [comment]
Here is the complete log : 


inside handle handleVerificationCode form
Footer.js:87 ........2.....handleVerificationCode. : 
Footer.js:88 123456
Footer.js:89 -----state: 
Footer.js:90 
{verificationCode: "123456", email: "xxx@gmail.com", password: "Asdf@123", errors: {…}, confirmpassword: "Asdf@123"}confirmpassword: "Asdf@123"
email: "xxx@gmail.com"errors: {cognito: null, blankfield: false}blankfield: falsecognito: null__proto__: Object
password: "Asdf@123"verificationCode: "123456"__proto__: constructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()

index.js:1 [ERROR] 44:25.578 AuthError - Confirmation code cannot be empty
console.<computed> @ index.js:1
ConsoleLogger._log @ ConsoleLogger.ts:91
ConsoleLogger.error @ ConsoleLogger.ts:142
AuthError @ Errors.ts:34
AuthClass.rejectAuthError @ Auth.ts:2068
AuthClass.confirmSignUp @ Auth.ts:347
Footer.handleVerificationCode @ Footer.js:93
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:306
executeDispatch @ react-dom.development.js:389
executeDispatchesInOrder @ react-dom.development.js:414
executeDispatchesAndRelease @ react-dom.development.js:3278
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:3287
forEachAccumulated @ react-dom.development.js:3259
runEventsInBatch @ react-dom.development.js:3304
runExtractedPluginEventsInBatch @ react-dom.development.js:3514
handleTopLevel @ react-dom.development.js:3558
batchedEventUpdates$1 @ react-dom.development.js:21871
batchedEventUpdates @ react-dom.development.js:795
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3568
attemptToDispatchEvent @ react-dom.development.js:4267
dispatchEvent @ react-dom.development.js:4189
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
discreteUpdates$1 @ react-dom.development.js:21887
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168

Footer.js:103 ERROR OCCURRED !!! ! ! !  !

**Comment by rajinonnet** [comment]
I am still getting this error, is there any work around ? 

Any help is really appreciated !

**Comment by duwerq** [comment]
@rajinonnet can you show the network request for Cognito confirmSignUp?

**Comment by rajinonnet** [comment]
I did not see any Network request for this Cognito confirmSignUp, its catching exception and throwing error.  Surprising !.

![image](https://user-images.githubusercontent.com/64529654/92157733-7965eb80-ee48-11ea-896c-c3aae22fbd86.png)

**Comment by duwerq** [comment]
I see the problem.  According the confirmSignUp docs, the parameters are:

`confirmSignUp(username: string, code: string, options?: ConfirmSignUpOptions)`

You're passing one object parameter to confirmSignUp instead of three separate parameters,

Change your confirmSignUp to:

```

          const confirmSignUpResponse = await Auth.confirmSignUp(
                        username:this.state.email,
                        code:this.state.verificationCode,
                        options : { forceAliasCreation: true }
               );
                console.log(confirmSignUpResponse);
            
        } catch (error ) {
            console.log("ERROR OCCURRED !!! ! ! !  ! ");
            this.setState({
              errors: { ...this.state.errors,cognito:error }
            });
        }
```

**Comment by rajinonnet** [comment]
Guys, I was able solve this issue.  The way i was calling the Cognito confirmSignUp was creating issues.

Thanks for prompt support guys ! 

**Here is the difference.**

**BEFORE ( which was throwing error )** 
```
          const confirmSignUpResponse = await Auth.confirmSignUp(
                    {
                        username:this.state.email,
                        code:this.state.verificationCode,
                        options : { forceAliasCreation: true }
                    }    
               );
```

**CORRECTED ONE ( WORKING )** 
`const confirmSignUpResponse = await Auth.confirmSignUp(this.state.email,this.state.verificationCode) ;
`

**Comment by rajinonnet** [comment]
@duwerq , yes you are correct, Now its working fine !  Thanks for your prompt reply.

Have a good day !
