### ISSUE TITLE
DataStore - Data won't be synchronized. No GraphQL endpoint configured. Did you forget `Amplify.configure(awsconfig)`?

### ISSUE THREAD

**Issue by synaptic-universal** [aws-amplify/community#325]
I have tried every solution but it is not working. Please help me.
@dabit3

**Comment by siegerts** [comment]
Hi 👋🏻 , this seems like it's related to Amplify JS. I recommend joining the [Amplify Community Discord server](https://discord.com/invite/amplify) `js-help` channel or [Discussions](https://github.com/aws-amplify/amplify-js/discussions) and pinging there to get some more eyes on it.  You may need to provide a bit more information though to give folks some context.
